### ISSUE TITLE
Replace PureRenderMixin with PureComponent

### ISSUE THREAD

**Issue by evoyy** [mlaursen/react-dd-menu#34]
Hi, thanks for creating this component!

The only thing I dislike is that it requires me to add an extra dependency to my package.json: *react-addons-pure-render-mixin*. Also, the React team are now discouraging this in favor of React.PureComponent:

> The PureRenderMixin mixin predates React.PureComponent. This reference doc is provided for legacy purposes, and you should consider using React.PureComponent instead.

https://facebook.github.io/react/docs/pure-render-mixin.html

I'd be happy to make a pull request, but PureComponent was only introduced this July in 15.3.0, and so it would cause problems for anyone who hasn't updated React since July, so I guess it would also require a version bump. I was wondering if/how you would like to handle this?

**Comment by mlaursen** [comment]
Yeah, I have been meaning to update this library after the 15.3.0 release of React, but I haven't had much time since I've been mainly focusing on my material design library.

I will be creating a `release/2.0.x` branch in a few minutes that you can make a pull request to if you are still willing to make one! Also, if you can get it in by 4:00 MST, I can also publish the 2.0.0 initial release today. Otherwise, It'll probably be late this week or early next week that I can update and publish.

I am also going to update the README a bit to say that I am not actively developing this project anymore since I think it is good as-is, but more than happy to still review/accept pull requests.

**Comment by mlaursen** [comment]
Ok, version 2.0.0 has been published and released. The `react-addons-pure-render-mixin` is no longer a required peer dependency.

**Comment by evoyy** [comment]
Thanks for doing this, it was actually on my todo list today. It's a simple change but I wanted to take the time to test it. In the end, I have rolled my own DropdownMenu with some modifications that suit my use case better. I borrowed some techniques from here. Cheers 👍
